### ISSUE TITLE
the code is very strange, two return?

### ISSUE THREAD

**Issue by liyuming1978** [Leonardo-Blanger/RefineDet_TensorFlow#2]
https://github.com/Leonardo-Blanger/RefineDet_TensorFlow/blob/5e758f37ec7729ebd95b2b20a85b12b008f1dc46/models/vgg16_reducedfc.py#L54

is it right?

**Comment by liyuming1978** [comment]
@Leonardo-Blanger

**Comment by Leonardo-Blanger** [comment]
That is reminiscent from the original implementation I had of that class, in which the call method returned only the final CNN output. I adapted it to return the features that were specified in the __init__ method, but left the rest of the code in there. After testing, I forgot to remove it. I will fix it soon, and until then, you can ignore it.

**Comment by sakaidesu-git** [comment]
Hello

I'm interested in the object detection technology.
I think that I want to customize from your base. 
If you can, could you tell me your srccode license?
